name: On tag creation
#on:
#  repository_dispatch:
#    types:[release_draft_new_version]
#on:
#  workflow_dispatch:
#    inputs:
#      logLevel:
#        description: 'Log level'
#        required: true
#        default: 'warning'
#      tags:
#        description: 'Test scenario tags'
on:
  release:
    types: [published]

jobs:
  print_some_stuff:
    runs-on: self-hosted
    env:
      RELEASE_VERSION: ${{ github.ref }}
    steps:
      - name: Get the version
        id: get_version
        run: |
          echo "::set-env name=MAGIC::${GITHUB_REF/refs\/tags\//}"
        if: startsWith(github.ref, 'refs/tags/')
      - name: just echo a message
        run: |
          echo $RELEASE_VERSION
          echo $MAGIC
          echo $VERSION
          echo "TAG: $GITHUB_TAG"
