name: Release drafter
#on:
#  repository_dispatch:
#    types:[release_draft_new_version]
#on:
#  workflow_dispatch:
#    inputs:
#      logLevel:
#        description: 'Log level'
#        required: true
#        default: 'warning'
#      tags:
#        description: 'Test scenario tags'
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  update_release_draft:
    runs-on: self-hosted
    env:
      RELEASE_VERSION: ${{ github.ref }}
      MAGIC: VERSION::${GITHUB_REF/refs\/tags\//}
    steps:
      - name: just echo a message
        run: |
          echo $RELEASE_VERSION
          echo $MAGIC
